on: push
name: Run phpunit test suite
jobs:
  phpunit-test-suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install composer dependencies
        run: |
          composer create-project juzaweb/laravel-cms cms
          cd cms
          composer require juzaweb/cms:dev-develop

