on: push
name: Run phpunit testsuite
jobs:
  phpunit-test-suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install composer dependencies
        run: |
          composer require "juzaweb/laravel-cms" "juzaweb/cms:dev-master" -q --no-interaction --no-update
      - name: Run Tests
        run: vendor/bin/phpunit vendor/juzaweb/cms
